# Generated by Django 5.1.4 on 2025-03-03 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=25,
                    ),
                ),
                ("content", models.TextField()),
                ("has_images", models.BooleanField(default=False)),
                (
                    "model",
                    models.CharField(help_text="The model provider ref ID name", max_length=120),
                ),
                ("provider", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="The name of the model", max_length=120, null=True
                    ),
                ),
                ("is_liked", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                ("generation_time", models.FloatField(blank=True, null=True)),
                ("prompt_tokens", models.IntegerField(blank=True, null=True)),
                ("completion_tokens", models.IntegerField(blank=True, null=True)),
                ("finish_reason", models.CharField(blank=True, max_length=50, null=True)),
                ("is_error", models.BooleanField(default=False)),
                ("has_citations", models.BooleanField(default=False)),
                (
                    "citations",
                    models.JSONField(
                        blank=True, help_text="List of citations for the message", null=True
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageError",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_code", models.CharField(blank=True, max_length=100, null=True)),
                ("error_title", models.CharField(max_length=255)),
                ("error_description", models.TextField()),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="error_detail",
                        to="completions.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageImage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.FileField(upload_to="message_images/%Y/%m/%d/")),
                ("order", models.IntegerField(default=0)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_images",
                        to="completions.message",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["created_at", "role"], name="completions_created_3024e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"], name="completions_convers_70dcee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageerror",
            index=models.Index(fields=["created_at"], name="completions_created_239c68_idx"),
        ),
    ]
