# Generated by Django 5.1.4 on 2025-03-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("completions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="has_tool_calls",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="tool_calls",
            field=models.JSONField(
                blank=True, help_text="List of tool calls made by the model", null=True
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="tool_results",
            field=models.JSONField(blank=True, help_text="Results of tool calls", null=True),
        ),
    ]
