# Generated by Django 5.1.4 on 2025-02-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("completions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="name",
            field=models.CharField(
                blank=True, help_text="The name of the model", max_length=120, null=True
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="provider",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="model",
            field=models.CharField(help_text="The model provider ref ID name", max_length=120),
        ),
    ]
