# Generated by Django 5.1.4 on 2025-02-23 23:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("completions", "0003_message_is_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageError",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_code", models.CharField(blank=True, max_length=100, null=True)),
                ("error_title", models.CharField(max_length=255)),
                ("error_description", models.TextField()),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="error_detail",
                        to="completions.message",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="completions_created_239c68_idx")
                ],
            },
        ),
    ]
