# Generated by Django 5.1.4 on 2025-03-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("completions", "0004_messageerror"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="citations",
            field=models.JSONField(
                blank=True, help_text="List of citations for the message", null=True
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="has_citations",
            field=models.BooleanField(default=False),
        ),
    ]
