# Generated by Django 5.0.4 on 2024-09-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="assistant",
            new_name="model",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
    ]
