# Generated by Django 5.0.4 on 2024-09-07 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, default=1, primary_key=True, serialize=False, verbose_name="ID"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assistant",
            name="sender",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistant",
                to="api.sender",
            ),
        ),
    ]
