# Generated by Django 5.0.4 on 2024-09-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assistant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="ai_models/")),
                ("description", models.TextField(blank=True, max_length=500, null=True)),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("default_temperature", models.FloatField(default=0.7)),
                ("default_max_tokens", models.IntegerField(default=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
