# Generated by Django 5.0.4 on 2024-09-09 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_assistant_message_model_remove_message_sender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assistant",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="message",
            name="meta_model",
        ),
        migrations.RemoveField(
            model_name="message",
            name="meta_user",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Sender",
        ),
    ]
