# Generated by Django 5.0.4 on 2024-09-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_assistant_id_alter_assistant_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="meta_model",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="meta_user",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
