# Generated by Django 5.0.4 on 2024-09-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_assistant_sender_remove_customuser_sender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
