# Generated by Django 5.0.4 on 2024-09-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_timestamp_conversation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='model',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
