# Generated by Django 5.1.4 on 2025-06-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providersettings",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("ollama", "Ollama"),
                    ("openai", "OpenAI"),
                    ("anthropic", "Anthropic"),
                    ("azure", "Azure OpenAI"),
                    ("google", "Google"),
                    ("openrouter", "OpenRouter"),
                ],
                max_length=50,
            ),
        ),
    ]
