# Generated by Django 5.1.4 on 2025-02-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Model",
        ),
        migrations.AddField(
            model_name="providersettings",
            name="options",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="providersettings",
            name="is_enabled",
            field=models.BooleanField(
                default=False, help_text="Whether this provider is enabled for the user"
            ),
        ),
    ]
