# Generated by Django 5.1.4 on 2025-06-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="max_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="system_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="top_p",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
