# Generated by Django 5.1.4 on 2025-01-19 23:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPrompt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("command", models.CharField(max_length=100, unique=True)),
                ("content", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Custom Prompts",
                "indexes": [
                    models.Index(fields=["command"], name="prompts_cus_command_9342aa_idx"),
                    models.Index(
                        fields=["user", "created_at"], name="prompts_cus_user_id_942124_idx"
                    ),
                ],
                "unique_together": {("command", "user")},
            },
        ),
    ]
