# Generated by Django 5.1.4 on 2025-02-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customprompt",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
