# Generated by Django 5.1.4 on 2025-02-04 04:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=100)),
                ("tokens", models.IntegerField(default=0)),
                ("cost", models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ("metadata", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "analytics_events",
                "indexes": [
                    models.Index(
                        fields=["user", "event_type", "timestamp"],
                        name="analytics_e_user_id_820d58_idx",
                    ),
                    models.Index(fields=["timestamp"], name="analytics_e_timesta_47536d_idx"),
                ],
            },
        ),
    ]
