# Generated by Django 5.1.4 on 2025-02-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsevent",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="tokens",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
