# Generated by Django 5.1.4 on 2025-02-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_alter_analyticsevent_cost_alter_analyticsevent_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsevent",
            name="completion_tokens",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="prompt_tokens",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
