# Generated by Django 5.1.4 on 2025-01-19 23:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.TextField(blank=True, null=True)),
                ("system_prompt", models.TextField(blank=True, null=True)),
                ("parameters", models.JSONField(default=dict)),
                ("enabled", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                ("capabilities", models.JSONField(default=dict)),
                ("parameters", models.JSONField(default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgentProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("display_name", models.CharField(max_length=100)),
                ("is_enabled", models.BooleanField(default=True)),
                ("requires_api_key", models.BooleanField(default=True)),
                ("supports_streaming", models.BooleanField(default=True)),
                ("supports_functions", models.BooleanField(default=True)),
                ("supports_vision", models.BooleanField(default=False)),
                ("default_parameters", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name_plural": "Agent Providers",
            },
        ),
    ]
