# Generated by Django 5.1.4 on 2025-03-03 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("display_name", models.CharField(max_length=100)),
                ("is_enabled", models.BooleanField(default=True)),
                ("requires_api_key", models.BooleanField(default=True)),
                ("supports_streaming", models.BooleanField(default=True)),
                ("supports_functions", models.BooleanField(default=True)),
                ("supports_vision", models.BooleanField(default=False)),
                ("default_parameters", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name_plural": "Agent Providers",
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.TextField(blank=True, null=True)),
                ("model", models.CharField(max_length=100)),
                ("system_prompt", models.TextField(blank=True, null=True)),
                ("parameters", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "display_name")},
            },
        ),
        migrations.CreateModel(
            name="AgentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
                ("capabilities", models.JSONField(default=dict)),
                ("parameters", models.JSONField(default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agents.agentprovider"
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "name")},
            },
        ),
    ]
