# Generated by Django 5.1.4 on 2025-03-03 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Knowledge",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("identifier", models.CharField(max_length=255, unique=True)),
                ("content", models.TextField()),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, max_length=255, null=True)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("file_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                        ],
                        default="ready",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Knowledge",
                "indexes": [
                    models.Index(fields=["identifier"], name="knowledge_k_identif_a5ee65_idx"),
                    models.Index(
                        fields=["user", "created_at"], name="knowledge_k_user_id_0450e5_idx"
                    ),
                ],
            },
        ),
    ]
