# Generated by Django 5.1.4 on 2025-03-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledge",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledge",
            name="file_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="knowledge",
            name="file_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledge",
            name="file_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="knowledge",
            name="status",
            field=models.CharField(
                choices=[("processing", "Processing"), ("ready", "Ready"), ("error", "Error")],
                default="ready",
                max_length=20,
            ),
        ),
    ]
