# Generated by Django 5.1.4 on 2025-03-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="inline_citations_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
