# Generated by Django 5.1.4 on 2025-03-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_settings_inline_citations_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="prompt_settings",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
