# Generated by Django 5.0.4 on 2024-08-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ollama_ip", models.CharField(blank=True, max_length=100)),
                ("ollama_port", models.CharField(blank=True, max_length=100)),
                ("ollama_default_model", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
