# Generated by Django 5.0.4 on 2024-08-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_conversation_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="conversation",
            old_name="timestamp_updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
